language: node_js
node_js:
- stable
script:
- yarn
- yarn test
- echo $TEST_VAR
- yarn build
cache:
  directories:
  - node_modules
before_install:
- yarn global add firebase-tools
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_API_KEY
  on:
    branch: dev
